export const SORT_USERS_BY_BANANAS = 'SORT_USERS_BY_BANANAS';
export const SEARCH_USER_BY_NAME = 'SEARCH_USER_BY_NAME';
export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';
export const SHOW_LOWEST_RANKED = 'SHOW_LOWEST_RANKED';